"""PydanticDeep assistant — deep agentic coding assistant.

PydanticDeep is built on PydanticAI and provides:
- Filesystem tools: ls, read_file, write_file, edit_file, glob, grep
- Task management: write_todos, planning subagent
- Subagent delegation
- Skills system (SKILL.md files)
- Memory persistence (MEMORY.md across sessions)
- Context file discovery (AGENTS.md, SOUL.md from workspace root)
- Built-in web search and web fetch

Backend types (set via PYDANTIC_DEEP_BACKEND_TYPE):
  "state"   — In-memory (default, no persistence)
  "daytona" — Daytona cloud workspace (isolated, cloud-native)

Configuration via settings:
  PYDANTIC_DEEP_BACKEND_TYPE  : "state" | "daytona" (default: "state")
  PYDANTIC_DEEP_INCLUDE_SUBAGENTS : enable subagent delegation (default: True)
  PYDANTIC_DEEP_INCLUDE_SKILLS    : enable skills system (default: True)
  PYDANTIC_DEEP_INCLUDE_PLAN      : enable planner subagent (default: True)
  PYDANTIC_DEEP_INCLUDE_MEMORY    : enable persistent MEMORY.md (default: True)
  PYDANTIC_DEEP_INCLUDE_EXECUTE   : enable shell execution (default: False)
  PYDANTIC_DEEP_WEB_SEARCH        : enable built-in web search (default: True)
"""

from __future__ import annotations

import time
from dataclasses import dataclass

from pydantic_ai import Agent
from pydantic_ai.tools import Tool
from pydantic_ai_harness import CodeMode

from backend.core.config import Settings
from backend.repositories.memory_repository import MemoryRepository
from backend.services.agent_factory import build_agent
from backend.services.rag_service import RagService
from pydantic_deep.deps import DeepAgentDeps

class AgentService:
    """Encapsulates agent construction, execution, and teardown.

    Uses lazy initialization so the agent is not built at import time.
    Accepts a ``Settings`` instance for testability (dependency injection).
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._agent: Agent[any, str] | None = None

    # ── Lifecycle ──────────────────────────────────────────────────────────

    def initialize(self) -> None:
        """Build the agent. Idempotent — safe to call multiple times."""
        if self._agent is not None:
            return

        memory_repo = MemoryRepository()
        rag_service = RagService()

        # The factory handles all complex initialization logic
        self._agent = build_agent(self._settings, memory_repo, rag_service)

    async def shutdown(self) -> None:
        """Release agent resources."""
        self._agent = None

    # ── Execution ──────────────────────────────────────────────────────────

    async def ask(self, prompt: str, session_id: str | None = None) -> AskResult:
        """Send a prompt to the agent and return the text output with usage stats."""
        self.initialize()
        assert self._agent is not None

        # Dependency injection using the repository's backend
        memory_repo = MemoryRepository()
        deps = DeepAgentDeps(backend=memory_repo.backend)

        t0 = time.monotonic()
        result = await self._agent.run(prompt, deps=deps)
        elapsed = time.monotonic() - t0
        usage = result.usage
        return AskResult(
            output=result.output,
            input_tokens=usage.input_tokens,
            output_tokens=usage.output_tokens,
            total_tokens=usage.input_tokens + usage.output_tokens,
            elapsed_seconds=round(elapsed, 2),
        )

@dataclass
class AskResult:
    """Result of a single agent ``ask()`` call with token usage information."""

    output: str
    """The agent's text reply."""

    input_tokens: int = 0
    """Number of prompt tokens sent to the model."""

    output_tokens: int = 0
    """Number of completion tokens generated by the model."""

    total_tokens: int = 0
    """Sum of input + output tokens."""

    elapsed_seconds: float = 0.0
    """Wall-clock time in seconds the agent took to respond."""

# ---------------------------------------------------------------------------
# Singleton — lazy-initialised on the first call to ``ask()``.
# Keeps the existing module-level ``ask`` facade so downstream imports in
# ``chat.py`` continue to work unchanged.
# ---------------------------------------------------------------------------

from backend.core.config import settings as _settings  # noqa: E402

_service = AgentService(_settings)

def get_service() -> AgentService:
    """Return the singleton AgentService instance."""
    return _service

async def ask(prompt: str, session_id: str | None = None) -> AskResult:
    """Send a prompt to the agent and return the text output with usage stats."""
    return await _service.ask(prompt, session_id=session_id)
